name: tod-api
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ secrets.APP_ENV }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      DB_CONFIG: ${{ secrets.DB_CONFIG }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=18.19.2'

      - run: npm install
      - run: npm build
      - run: npm test
        